### ISSUE TITLE
Error due to race hazard: read_file_contents: Reading file "/proc/5842/stat" failed

### ISSUE THREAD

**Issue by timbunce** [collectd/collectd#1017]
We get these errors reported fairly regularly. This looks like a simple race-hazard: collectd opens the /proc/$pid/stats file ok but by the time it gets to read it the process has exited.

Since failure to open the file is handled _silently_ (by returning -1) I suggest that failure to read is handled the same way, e.g., just downgrade the ERROR to a DEBUG. (I'd be happy enough with downgrading to WARNING but that still seems like overkill.)

I'd also like to change the message so it _includes the actual underlying error message_.

Let me know what you'd prefer and I'll submit a PR for you.

**Comment by mfournier** [comment]
@timbunce thanks for tracking this down ! So I suppose this would be the "processes" plugin ?

It would indeed make sense to silently ignore the read error if it's already what is done for openening the file. Also +1 for a more useful messages !

As this can be classified as a bug, would you mind submitting your patch against the collectd-5.3 branch (so that it also ends up in the branches of the more recent versions). Thanks!

**Comment by timbunce** [comment]
Great. Done. See PR #1018.

**Comment by timbunce** [comment]
Oops. Wrong branch. I'll redo in a moment.

**Comment by timbunce** [comment]
Hah. No I won't... the read_file_contents() function in src/common.c has already been rewritten in the collectd-5.3 branch and no longer has the ERROR call. I'll close the issue. Short and sweet. Thanks!

**Comment by Farfaday** [comment]
I am sorry to reopen such an old ticket, but it seems to me that this is still an issue. (at least in 5.9.0, we are regularly getting  _processes plugin: read_file_contents: Reading file "/proc/xxxx/stat" failed_ in the logs)


In https://github.com/collectd/collectd/blob/master/src/utils/common/common.c#L1304 (current master)    P_ERROR is still used...
