### ISSUE TITLE
statsd plugin: millisecond conversion?

### ISSUE THREAD

**Issue by falzm** [collectd/collectd#1020]
Hi

I observe weird results with statsd plugin when sending timing metrics. According to the [original documentation][0] and [examples][1] timings are to be sent at a millisecond resolution – e.g. `some_metric:42.0|ms` – however I can't get my head around why collectd stores these divided by 1000 (i.e. `0.042`).

From what I've understood reading the [plugin's code][2], when a metric is parsed the timing value is converted to collectd's internal `cdtime_t` struct using the `MS_TO_CDTIME_T` macro, but I guess when collectd dispatches values to other write plugins it uses the reverse macro `CDTIME_T_TO_MS` to convert is back to the original milliseconds value... so how come the original timing values end up divided by 1000?

I'm quite confused about this issue, sorry if I missed something obvious.

[0]: https://github.com/etsy/statsd/blob/master/docs/metric_types.md
[1]: https://github.com/collectd/collectd/issues/401#issue-18048129
[2]: https://github.com/collectd/collectd/blob/collectd-5.4.1/src/statsd.c#L260

**Comment by tmm1** [comment]
I'm seeing the same behavior as well.

**Comment by tmm1** [comment]
> it uses the reverse macro CDTIME_T_TO_MS to convert is back to the original milliseconds value

It doesn't look like the value is ever converted back to milliseconds. It uses `CDTIME_T_TO_DOUBLE` which just returns the time in seconds as a float, which is why values downstream appear in seconds instead of milliseconds.

**Comment by tmm1** [comment]
So basically this is a known issue in collectd. I'm working around it by multiplying values by 1000 to convert them back into milliseconds in https://github.com/github/enterprise2/pull/4103.

I also pulled in the patches to fix percentiles into that PR.

**Comment by falzm** [comment]
Hi Aman  

The link you've provided to your PR doesn't work, could you please check?

Thank you

**Comment by tmm1** [comment]
Sorry that was a private PR I didn't mean to link here. There are some patches on the 5.4 branch that haven't been released in any version yet:

```
Changes to the next 5.4 release
StatsD plugin: utils_latency: Two division by zero error conditions have been corrected. Thanks to Wilfried Goesgens. #655
StatsD plugin: utils_latency: Support for including values above 1000 in percentile calculation has been added. Thanks to Yoga Ramalingam. #401
```

but neither of them fixes the millisecond conversion issue. My workaround was to multiply values by 1000 to convert them back to milliseconds at the UI layer.

**Comment by octo** [comment]
That is by design: *collectd* uses the base units as much as possible, to let front-ends correctly scale metrics, e.g. to milliseconds. Else, you often end up with graphs showing "kilo-milliseconds" and similar.

**Comment by falzm** [comment]
Thanks for your input @octo. However, I don't really agree with you on this: to me, collectd should stay neutral to incoming data and metrics should remain in their original scales – especially in the statsd module, where the sender controls the scale. WDYT?

**Comment by tmm1** [comment]
@falzm I agree with you, but if everyone has been storing metrics in seconds it seems unwise to suddenly switch to milliseconds and break everyone's graphs. Perhaps a patch to add a new option that lets you switch away from the default is best, something like `TimerMilliseconds true`

**Comment by falzm** [comment]
Good idea @tmm1.

**Comment by octo** [comment]
@falzm collectd was never really "neutral" in the way it handled data. For example, the "df" plugin:
* It converts the data to *bytes*, rather than reporting *blocks*.
* It reports *used*, *reserved* and *free* disk space, not *total*, *available* and *free*, as provided by UNIX. The reason is that the sum of all "partitions" should always yield the total, again to make graphing / evaluating easier.

I'd question how much control the sender has about the scale in the statsd case, since the protocol *specifies* the use of milliseconds. Further, the spec basically implies integers (numbers in the range <code>[0,&nbsp;2^64-1]</code>), making sub-millisecond measurements impossible. [*]

On the other hand, I don't see an advantage from storing timers in milliseconds. Why do you think this is a good thing to do? What would become easier if collectd reported milliseconds instead of seconds?

Best regards,
—octo

[*] Not entirely true in our case, though: collectd's implementation diverges from [the spec](https://github.com/b/statsd_spec) by parsing the timer value as a double ("48bit precision ought to be enough" – the longest period it can parse without loss of precision is a little under 9000 years) and allowing a scale to be added with <code>@…</code>.

**Comment by falzm** [comment]
@octo I meant neutral for plugins that are "passive" in the metrics processing, that is only receive metrics already measured/collected by other tools – such as `statsd`. I find odd that this plugin explicitly accepting values in milliseconds isn't keeping the original scale – and it looks like I'm not the only one. But as you said if there is a constraint about handling certain scales then I understand your stand.

Anyway, no drama here – now that I'm aware of this "feature" I can work around it ;)

**Comment by tmm1** [comment]
I noticed a similar issue with counters where they seem to be divided by 10.

If I submit 99 using `echo "counter_test:99|c" > /dev/udp/127.0.0.1/8125`, the rrd file says 9.

**Comment by robrwo** [comment]
The problem with this is that timings are used as a generic histogram for statsd servers that do not support the histogram metric.
