### ISSUE TITLE
Mixed usage of sfree() & free() in plugin.c

### ISSUE THREAD

**Issue by michaelsalmon** [collectd/collectd#1136]
In plugin.c line 291 key is freed using free() but on line 310 sfree() is used. If I understand sfree() correctly then it should be called as sfree(&key) or free(key) should be used.

As these 2 lines are on error paths it may well be that there is rarely any problem.

This may be the cause of the corruption in issue 1110.

**Comment by octo** [comment]
Hi @michaelsalmon,

thanks for raising this issue.
```c
sfree (ptr);
```
is equivalent to
```c
free (ptr);
ptr = NULL;
```
and is used to make use-after-free situations more severe, i.e. they hopefully crash the daemon, so we can easily fix them. Ideally, we'd use `sfree()` everywhere. Would you be willing to create a patch for this?

#1110 has another root cause though. I've added an update there as well.

Best regards,
—octo

**Comment by michaelsalmon** [comment]
I have changed sfree(key) to free(key) in pull request 1137. I chose this over sfree(key) as key is never used again in that function.

If you prefer sfree() could you add that comment to the pull request.

**Comment by octo** [comment]
Fixed by 3ba3bdfa3d71a63ee1d275c949d9da527abd31a6
