### ISSUE TITLE
Buffer overflow in virt.c?

### ISSUE THREAD

**Issue by wojt** [collectd/collectd#1150]
Shouldn't the line at https://github.com/collectd/collectd/blob/master/src/virt.c#L170:

n = DATA_MAX_NAME_LEN - strlen (vl->host) - 2;

Be:

n = DATA_MAX_NAME_LEN - strlen (vl->host) - 1;

?

Consider if the code below (host and domain can be set by the user):

case hf_name:
            name = virDomainGetName (dom);
            if (name)
                strncat (vl->host, name, n);
            break;

name is 63 characters long.

It will make:

n = DATA_MAX_NAME_LEN - strlen (vl->host) - 2;

n = 64 - 63 -2 = -1

Then, for example:

strncat (vl->host, uuid, n);

Will call strncat with n == -1 which will be converted to unsigned int -- buffer overflow.

**Comment by rubenk** [comment]
I don't think you're correct and that n will never go negative. Please correct me if I'm wrong.

We start with n = 64 - 0 - 2 = 62.
In the first iteration of the loop, strncat (vl->host, name, n) copies up to 62 characters + terminating \0.
If name >= 63, after that n = 64 - 62 - 2 = 0 and the loop terminates.
If name < 63 and we have more than one field, there's still bytes free which we need for the strncat (vl->host, ":", 1), since that overwrites the terminating \0 of vl->host with ":" and add a terminator.

There is another issue here of course in that DATA_MAX_NAME_LENGTH is pretty small and we don't detect truncation.

**Comment by wojt** [comment]
Ach, you're right. Sorry!

**Comment by rubenk** [comment]
No problem, better safe than sorry ;)

**Comment by wojt** [comment]
I only think it would be really useful to mention the 63 characters limit in the docs for vitr plugin. It's easy to reach the limit when one uses UUID / hostname / domain name combination.If one relies on this data, (e.g. UUID coming from collectd to identify VMs) then it might be surprising if UUID gets truncated. UUID alone is 36 characters.

**Comment by rubenk** [comment]
62 character limit ;)
Sure, are you able to send a pull requests against the manpage? https://github.com/collectd/collectd/blob/master/src/collectd.conf.pod

**Comment by wojt** [comment]
Of course :-).

Sure, will do that. Thanks.

**Comment by mfournier** [comment]
Closed by 9dcc5ed, thanks !
