### ISSUE TITLE
massive aggregation plugin log errors

### ISSUE THREAD

**Issue by iaean** [collectd/collectd#1193]
Hi @tokkee, @octo,

I'm using the aggregation plugin on a collectd collector, that's receiving data via the network plugin. Version is 5.4.1.

The problem is, that trillions of

```
aggregation plugin: Unable to read the current rate of "hostA/cpu-7/cpu-softirq".
utils_vl_lookup: The user object callback failed with status 2.
utils_vl_lookup: The user object callback failed with status 2.
aggregation plugin: Unable to read the current rate of "hostB/cpu-7/cpu-steal".
```

flooding the log with Gigabytes per day. So we had to disable this great aggregation feature for the meantime.

It would be great, if you can investigate here a little bit. I am looking forward to give you any assistance.

Because I found a couple of similar issues, I tried versions 5.4.2 and 5.5.0, too. Without success.

The clients running with collectd defaults for Interval/Timeout.
The relevant server config looks like:

```
Interval     30
Timeout      2
ReadThreads  6
WriteThreads 6

LoadPlugin aggregation
<Plugin "aggregation">
  <Aggregation>
    Plugin "cpu"
    Type "cpu"
    SetPlugin "cpu"
    SetPluginInstance "summary-%{aggregation}"
    GroupBy "Host"
    GroupBy "TypeInstance"
    CalculateNum true
    CalculateSum true
    CalculateAverage true
    CalculateMinimum true
    CalculateMaximum true
    CalculateStddev true
  </Aggregation>
</Plugin>

PreCacheChain "PreCache"
<Chain "PreCache">
  # Aggregate and filter annoying CPU plugin stuff
  <Rule "CpuAggregation">
    <Match "regex">
      Plugin "^cpu$"
      PluginInstance "^[0-9]+$"
    </Match>
    <Target "write">
      Plugin "aggregation"
    </Target>
    Target "stop"
  </Rule>
</Chain>
```

Thanks for your patience.
I'm always excited to hear from you.
Best regards

**Comment by shibenja** [comment]
In our case, the problem is specific to 5.7.1, and the following patch fixes the racing condition in uc_check_timeout():

--- a/5.7.1/collectd-5.7.1/src/daemon/utils_cache.c     Wed Mar 22 17:52:20 2017 +0000
+++ b/5.7.1/collectd-5.7.1/src/daemon/utils_cache.c     Mon May 08 17:38:40 2017 +0000
@@ -222,7 +222,7 @@
 } /* int uc_init */
 
 int uc_check_timeout(void) {
-  cdtime_t now = cdtime();
+  cdtime_t now;
 
   struct {
     char *key;
@@ -232,6 +232,7 @@
   size_t expired_num = 0;
 
   pthread_mutex_lock(&cache_lock);
+  now = cdtime();
 
   /* Build a list of entries to be flushed */
   c_avl_iterator_t *iter = c_avl_get_iterator(cache_tree);

**Comment by sradco** [comment]
I encountered this issue as well.

**Comment by octo** [comment]
Hi, thanks for reporting this / following up!

The regression mentioned by @shibenja was introduced in 5.7.0 with commit 2ede5e7fd0f7e75edd1fba531cd870bb16092e71. A commit with the fix is coming up. Unfortunately the regression is too recent to be the problem of the original reporter. I assume 5.7 works for you with the posted fix?

Best regards,
—octo

**Comment by sradco** [comment]
@octo , Hi, How do I know in which build we can get this fix in?

**Comment by octo** [comment]
@sradco I'm planning to releasing a new version soon, but my private life is a bit busy at the moment, do I can't promise a concrete date. I'll do my best to get this out this week though.
