### ISSUE TITLE
write_kafka outputs key value as bytes and not string

### ISSUE THREAD

**Issue by cj-wilson** [collectd/collectd#1283]
When specifying a Topic and Key write_kafka writes the key as bytes or int (can't tell) which makes viewing keys through tools like kafkacat or python shell difficult.

As a Kafka consumer I would like the ability to perform a compare against the key in a simplified way.

Details:  

collectd: current master branch
librdkafka: current master branch
Kafka: kafka_2.9.2-0.8.2.1
Linux: 2.6.32-220.el6.x86_64
RHEL 6.2

-Chris

**Comment by cj-wilson** [comment]
Using the python client (and kafkacat) the type does come back as below:

1. string of bytes(?)
2. length of string
3. type

('S\x1f\xfe\xc9', 4, <type 'str'>)

-Chris

**Comment by mfournier** [comment]
@pyr, any thoughts on this ?

**Comment by pyr** [comment]
sounds reasonable.

**Comment by nitreason** [comment]
is that means the 'string' type value  didn't supported  yet?   
 I have a problem as follow :
I'm using collectd snmp plugin to get the SN of a cisco router.  And then send it to the kafka though write_kafka plugin. But now i got an different issue like this:
   -- [root@TEST ~]# /opt/kafka/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic collectd1
       Core_SW_Huawei.snmp.SN-SN 2102352360 1446709755

   --[root@TEST ~]# snmpwalk -v 2c -c XXXXXXXX <My Ip adress> 1.3.6.1.2.1.47.1.1.1.1.11.201326593
SNMPv2-SMI::mib-2.47.1.1.1.1.11.201326593 = STRING: "2102352360W0E8000041"

**Comment by nitreason** [comment]
@pyr  please help.

**Comment by octo** [comment]
FTR, the *write_kafka plugin* appears to calculate the CRC32 of the provided key and uses that going forward. `rd_kafka_produce()` expects `const void *key` and `size_t keylen`, so providing something like
`(…, key, strlen (key), …)` instead of a uint32_t should be fairly simple.

The *librdkafka* documentation claims that the key is optional. Why does the *write_kafka plugin* generate a new random 32bit integer for each message when the user didn't specify a key? Can't we just pass `(NULL, 0)` in that case? @pyr, do you remember?

Also, we should really fix that use of `rand()` – it's not thread safe.

**Comment by pyr** [comment]
Hi @octo,

Adding a key here was to ensure that consumers would see a consistent subset of metrics for a specific topology (one of the great features of kafka).
