### ISSUE TITLE
Could not find plugin on AIX 7100-03-05-1524

### ISSUE THREAD

**Issue by sah44** [collectd/collectd#1306]
```
collectd -T

plugin_load: Could not find plugin "syslog" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "cpu" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "interface" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "load" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "memory" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "network" in /opt/fil-collectd/usr/lib64/collectd
Found a configuration for the `network' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Found a configuration for the `network' plugin, but the plugin isn't loaded or didn't register a configuration callback.
No read-functions are registered.
Exiting normally.
collectd: Stopping 5 write threads.
```

files exit in the following location
```
/opt/fil-collectd/usr/lib64/collectd/cpu.a
/opt/fil-collectd/usr/lib64/collectd/cpu.la
/opt/fil-collectd/usr/lib64/collectd/interface.a
/opt/fil-collectd/usr/lib64/collectd/interface.la
/opt/fil-collectd/usr/lib64/collectd/load.a
/opt/fil-collectd/usr/lib64/collectd/load.la
/opt/fil-collectd/usr/lib64/collectd/memory.a
/opt/fil-collectd/usr/lib64/collectd/memory.la
/opt/fil-collectd/usr/lib64/collectd/network.a
/opt/fil-collectd/usr/lib64/collectd/network.la
```

**Comment by octo** [comment]
*collectd* is looking for `network.so`, a shared library. The `network.a` file is probably a static library, which collectd can't load at runtime.

**Comment by colomboipl** [comment]
Do you resolve the issue ?

**Comment by colomboipl** [comment]
I have the same problem

**Comment by ddaka** [comment]
Hi i'm having the same issue with collectd-5.5.0  with options ./configure --disable-rrdtool --disable-ipc --enable-shared on AIX 6100-09 , also i have excluded collectd-tg from Makefile since its was failing to compile, 
@octo, how did you solve this? 

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/4.8.3/lto-wrapper
Target: powerpc-ibm-aix6.1.0.0
Configured with: ../gcc-4.8.3/configure --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --host=powerpc-ibm-aix6.1.0.0
Thread model: aix

**Comment by sah44** [comment]
I have not resolved the issue yet. I do need to resolve this issue. But I have not had time to relook at this problem

**Comment by colomboipl** [comment]
I want to know if collectd 5.5.0 works on AIX 5.2.0 . If not tell directly, because I will not spend more time with this issue on my head.
In my tests I do:

./configure --disable-lpar --disable-ipc CXX=xlC 
Then before "make" I have to erase the collectd-tg entry on the file "src/Makefile"
Then "make" and "make install"
When I run the command /opt/collectd/sbin/collectd -T it appears, the error:
plugin_load: Could not find plugin "syslog" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "cpu" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "interface" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "load" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "memory" in /opt/fil-collectd/usr/lib64/collectd
plugin_load: Could not find plugin "network" in /opt/fil-collectd/usr/lib64/collectd
Found a configuration for the `network' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Found a configuration for the `network' plugin, but the plugin isn't loaded or didn't register a configuration callback.
No read-functions are registered.
Exiting normally.
collectd: Stopping 5 write threads.

**Comment by colomboipl** [comment]
hello i found this usefull. i will try this for next year :)

1) generate the libxy.so.x like before from the static library libxy.a with the linker.
2) Now remove the static library libxy.a
3) We now need to recreate libxy.a as a dynamic library by using the ar -cr libxy.a libxy.so.x
4) And finally only install libxy.a not the libxy.so library.
Since linking is dynamic on AIX now, as in newer versions, executables have to find it’s associated libraries even if the library is not installed in one of the standard /lib or /usr/lib library paths.

reply if this works.

**Comment by bharatjosh** [comment]
Has this been resolved. I am also facing exactly the same issue. Want to try  @colomboipl answer but not sure how and where to make this change? Can someone please help
