### ISSUE TITLE
Write_Kafka CollectD 5.5

### ISSUE THREAD

**Issue by MikeMester** [collectd/collectd#1477]
Trying to setup collectd to write to kafka in our enterprise.  It seems that the plugin is not part of the EPEL 7 repo.  Is there a way to manually install or is there another source I can grab it from.  Message in my logfile is:

Systemd: Starting Collectd statistics daemon...
Dec 18 14:25:49 persist collectd[9765]: plugin_load: Could not find plugin "write_kafka" in /usr/lib64/collectd
Dec 18 14:25:49 persist collectd[9765]: Found a configuration for the `write_kafka' plugin, but the plugin isn't loaded or didn't register a configuration callback.

Thanks,

Mike

**Comment by rubenk** [comment]
Hi Mike,

The write_kafka plugin needs the rdkafka library, which isn't packaged for EPEL, or Fedora for that matter.

**Comment by MikeMester** [comment]
Thanks Rubenk,  I was hoping that wasn't the case.  Wondering where I go from here?  Any suggestions?  Changing the OS isn't an option.

**Comment by rubenk** [comment]
The best way forward is to package rdkafka for Fedora / EPEL. Unfortunately I don't have the time or the interest to do that myself, but if you need any help with creating an rpm, let me know.

When you get it into EPEL I'm willing to rebuild collectd in EPEL with support for write_kafka.

Since this isn't an upstream issue I'm going to close it, but feel free to contact me with any questions!

**Comment by heaje** [comment]
Since this issue was open and closed it looks like librdkafka was put in EPEL.  I just tested building Collectd 5.7.1 on CentOS 7 with write_kafka enabled using the EPEL provided libraries and it worked fine.  Can this issue be revisited at this point?

**Comment by rubenk** [comment]
I enabled the write_kafka plugin in collectd 5.8, which is in epel-testing at the moment (https://koji.fedoraproject.org/koji/buildinfo?buildID=1004593)
