### ISSUE TITLE
collectd running in foreground can't be stopped with Ctrl-C when python plugin is loaded

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#1848]
I understand from collectd-python(5) that SIGINT will be blocked when in an interactive session, but I have set Interactive set to false.

**Comment by rubenk** [comment]
I see that running the python module blocks indeed blocks SIGINT.

Without loading python:
```
 grep SigBlk /proc/$(pgrep collectd)/status
SigBlk:	0000000000000000
```

With loaded python:
```
$ grep SigBlk /proc/$(pgrep collectd)/status
SigBlk:	0000000000000002
```

@trenkel any idea what could cause this?

**Comment by trenkel** [comment]
Ah, yes, if SIGINT is using the default handler when Python is initialized it will install its own handler:
https://github.com/python/cpython/blob/origin/2.7/Modules/signalmodule.c#L1042

Best way around this would probably be to change it back to SIG_DFL using the python methods in order to not confuse the interpreter about the current state of things.

signal.signal(signal.SIGINT, signal.SIG_DFL)

And then a bit later this module blocks it:
https://github.com/collectd/collectd/blob/master/src/python.c#L986

Which should probably only happen in interactive mode. I'll need to experiment a bit to figure out the best way to do this. Signal handling with threads is always such a mess.

**Comment by rubenk** [comment]
Great, thanks for looking into this!
