### ISSUE TITLE
Adding units as a new field

### ISSUE THREAD

**Issue by sradco** [collectd/collectd#2047]
*   Version of collectd:5.5.2
*   Operating system / distribution: Red Hat Linux

## Expected behavior

I would want to have a filed that holds the metric unit.
This missing info is important for better metric definition.

## Actual behavior

No units. Requires investigation for each metric.

**Comment by maryamtahhan** [comment]
I believe the unit for a metric is covered by the type in collectd? or is this something different?

**Comment by sradco** [comment]
No. It's not specific for units.

**Comment by octo** [comment]
Thanks for openeing this @sradco!

I absolutely agree, having a "unit" associated with each metric would be absolutely brilliant! The *Metrics 2.0* spec even goes so far as making this information one of only two mandatory labels. Unfortunately, adding this to collectd is a nontrivial task and is probably quite some work.

As @maryamtahhan already pointed out, the *types* kind of fill in for an explicit "unit" field currently: "df" implies "bytes", "cpufreq" implies "Hertz", "frequency" implies "s^-1" and so on. Some are a bit ambiguous, for example I'm not sure whether "charge" is "Ah" or "Wh", and many imply the same unit.

Best regards,
—octo

**Comment by YmrDtnJu** [comment]
One idea whould be to remove the need for types and replace that with units. I think types are currently only necessary because some types have more than one value at the same time. If those types just get split up into one type (or then unit) per value, types would not be necessary anymore. Additionally, a flag could tell, if a value is a gauge (like the number of bytes received on a network interface) or a rate (like the number of bytes received on a network interface during the last interval).

The big advantage would be, that each plugin can simply tell what type of data it collects without any need to configure that on the client collectd instance AND the one on a server, that receives values via the network plugin.
Applications that draw graphs can also create better graphs without knowing all types of all plugins in advance because all they need, is the name of the host, the name of the value itself and maybe the name of an instance of that value if such instance exists. Currently, types are required to figure that out.
