### ISSUE TITLE
dmesg printout 'IPMI message handler: Event queue full, discarding incoming events' after collectd start 

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#2102]
*   Version of collectd: 5.4
*   Operating system / distribution: centos 6

## Expected behavior

no except occur when collectd start

## Actual behavior
```
dmesg | grep IPMI:
IPMI message handler: Event queue full, discarding incoming events
```

## Steps to reproduce

*   OpenIPMI 2.0.16 or OpenIPMI-2.0.22
*   service q-collectd start and collectd run several	 days
*   service restart
*   dmesg | grep IPMI

**Comment by rpv-tomsk** [comment]
> Actual behavior
> 
> dmesg | grep IPMI:
> IPMI message handler: Event queue full, discarding incoming events
> 

Did you have exactly one line?

If no, can you please provide info:

#Number of lines before restart
dmesg | grep IPMI: |wc -l
#Do collectd restart
collectd restart
#Number of lines after restart
dmesg | grep IPMI: |wc -l

Thanks.

**Comment by rpv-tomsk** [comment]
All the things happens at kernel level. 

You have some events in BMC. Collectd does not receive these events (and should not), and that is implemented correctly at Collectd level. Due to that, unhandled messages are enqueued in driver, but only 25 events can be in queue. You have more than 25 events and that leads to messages in the log.

Related source: http://lxr.free-electrons.com/source/drivers/char/ipmi/ipmi_msghandler.c?v=3.12 (there is no source for 2.6 branch)

**Comment by rubenk** [comment]
@rpv-tomsk so this is not a collectd issue? Let's close this then.

**Comment by rpv-tomsk** [comment]
Collectd currently not uses `ipmi_sensor_add_threshold_event_handler ()`, `ipmi_sensor_add_discrete_event_handler ()` or something like these functions, it does not asks for events currently. But interface is opened and events arrive anyway, as we can see. If nobody handles them, which is happened because no other program uses IPMI, then kernel prints message.

Currently IPMI events are not supported in Collectd. When Collectd will support events, then there will be no such messages.

That support can be added via stub too, but there is PR about IPMI events support / Collectd notifications exists here on github.

**Comment by vmytnykx** [comment]
#2091 (IPMI events support) just for referencing... 

Thanks and Regards,
Volodymyr

**Comment by rpv-tomsk** [comment]
If you do not have this problem anymore, can we close this issue?
