### ISSUE TITLE
pkg-ci release of dns plugin doesn't run under CentOS 7

### ISSUE THREAD

**Issue by xyntrix** [collectd/collectd#2186]
*   Version of collectd:
```
collectd-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-curl-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-disk-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-dns-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-ipmi-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-netlink-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-ping-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
```
```
# cat /etc/collectd.d/20-dns.conf
LoadPlugin dns
```
*   Operating system / distribution:
CentOS Linux release 7.3.1611 (Core)

## Expected behavior

DNS plugin works

## Actual behavior

dns plugin: Running collectd as root, but the CAP_NET_RAW capability is missing. The plugin's read function will probably fail. Is your init system dropping capabilities?
dns plugin: Opening interface `any' failed: any: You don't have permission to capture on that device (socket: Operation not permitted)

Loaded basic DNS plugin and plugin errors out to syslog, complaining about permission issue.

## Steps to reproduce

* Install collectd from pkg-ci release under CentOS 7
* Configure dns module
* Start collectd
* View log and note dns module not loading

I believe this is because the DNS plugin is trying to use interface name of literal "any" which is invalid.  I can manually set the interface here -- but across my fleet of boxes with many varied interfaces, I'd like this to just work as it did in 5.4 -- no specific interface configuration required.

**Comment by rubenk** [comment]
> I believe this is because the DNS plugin is trying to use interface name of literal "any" which is invalid.

No it's not, it's because of this:

> dns plugin: Running collectd as root, but the CAP_NET_RAW capability is missing. The plugin's read function will probably fail. Is your init system dropping capabilities?

Collectd running under systemd still runs as root, but drops capabilities for security reasons. There are a few plugins which need more access though, dns and ping among others. This is described in the systemd unit (https://github.com/collectd/collectd/blob/collectd-5.7.1/contrib/systemd.collectd.service#L14), probably /etc/systemd/system/collectd.service on your system.

**Comment by xyntrix** [comment]
I'll get this tested and figure out a way for us to auto-configure for our fleet.  Would it be appropriate for the collectd-plugin pkg-ci release packages for ping/dns to set these permissions automatically? Perhaps via a post-install step?

**Comment by rubenk** [comment]
I'm not sure, that means that a soon as you install the dns plugin your config is changed and permissions for the collectd process are increased. I think it's better if an admin has explicit control over this. Apart from that it's quite hard to implement since the config file can be anywhere, including in systemd's dropin directories.

**Comment by xyntrix** [comment]
I verified why this stopped working for us, in prior versions (collectd 5.6?) the systemd configurations didn't drop privs -- where that is now the case in 5.7.  This might be a bit of a breaking change for folks doing an in-line upgrade who don't happen to catch those lines buried in the systemd stanza.   

At any rate, adding the privs to an override doesn't actually work.  I'd have to modify the vendor provided systemd file, which goes against the design ideals of systemd files from vendors.  Normally, this would be easily overriden in CentOS by adding the following: to /etc/systemd/system/collectd.service.d/override.conf:
```
[Service]
CapabilityBoundingSet=
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN CAP_NET_RAW CAP_SYS_RAWIO
```
It looks like someone else ran into this issue: it is not currently possible to override the CapabilityBoundingSet in systemd under CentOS 7:

https://bugzilla.redhat.com/show_bug.cgi?id=1409586

It's not clear when the fix will be pushed into the RHEL7 stable release. 

It would be awesome if there was another way around this that didn't involve manipulating systemd configs by the end user.   Are there solid security concerns which prompted the change to dropping privs under systemd in the 5.7 release?

**Comment by xyntrix** [comment]
I see now where this was introduced, to drop privs as of 5.6 and 5.7 code lines:
https://github.com/collectd/collectd/commit/ace895b049403752623dcbca2496c20cf64e495e

So there's another problem this introduces.  This adds inside of the systemd environment mount points of /etc, /boot, and /usr that do not exist outside of this systemd environment.  

At ~12:50 here I changed from using the old systemd to the newer systemd which adds drop privs, and now I have additional mount points that do not exist outside of the systemd process space.

![image](https://cloud.githubusercontent.com/assets/1305762/23278083/83085d62-f9cd-11e6-9374-04fa05c566e3.png)


```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      3064  0.0  0.3 838716  6260 ?        Ssl  12:49   0:01 /usr/sbin/collectd -C /etc/monitoring/collectd.conf

[root@fluffyclouds ~]# cat /proc/3064/mounts | egrep 'usr|boot|etc'
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
/dev/vda1 /boot ext4 ro,relatime,data=ordered 0 0
/dev/vda1 /etc ext4 ro,relatime,data=ordered 0 0
/dev/vda1 /usr ext4 ro,relatime,data=ordered 0 0

[root@fluffyclouds ~]# cat /proc/mounts  | egrep -i 'usr|boot|etc'
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
```

**Comment by rubenk** [comment]
> I verified why this stopped working for us, in prior versions (collectd 5.6?) the systemd configurations didn't drop privs -- where that is now the case in 5.7. This might be a bit of a breaking change for folks doing an in-line upgrade who don't happen to catch those lines buried in the systemd stanza.

If I'm not mistaken, this was 4fd7396fb96498b3dc1ef95361b6b0f0c7e125c3, which has been backported to 5.5.1, 5.6.1 and 5.7.1

**Comment by rubenk** [comment]
> It looks like someone else ran into this issue: it is not currently possible to override the CapabilityBoundingSet in systemd under CentOS 7: https://bugzilla.redhat.com/show_bug.cgi?id=1409586. It's not clear when the fix will be pushed into the RHEL7 stable release.

That's very unfortunate, this has bitten me recently as well for some other packages.

Since this essentially makes the dns, ping and other plugins unusable on RHEL7, I'm not opposed to reverting this change temporarily.

> Are there solid security concerns which prompted the change to dropping privs under systemd in the 5.7 release?

Yes of course, collectd running as root with an enormous amount of plugins that all use an even bigger amount of shared libraries, external services etc make a pretty big attack surface.

Meanwhile, with my downstream EPEL maintainers hat on, might I suggest for now that you use the collectd packages from EPEL? I tend to be somewhat conservative for what I enable in EPEL and it has a different unit without these restrictions.

**Comment by xyntrix** [comment]
Using epel is something to consider...  My use case is i'm trying to build out enterprise infrastructure where we have managed collectd install as a standard across all our varying hosts (mostly centos).  I'd be great to align version/features as close as we can with a common version.. previously, I was building my own collectd -- with the pkg-ci stuff added over the last year.. I want to switch to using those rpms, with some quarterly review update/cadence from the pkg-ci repos.   Some of the challenge lies in supporting Cent6 where epel is not quite as current with the collectd updates.   I greatly appreciate all the work you all have put into the collectd project and hope to not just consuming also contributing a bit more in terms of helping fix issues and provide testing.      I'll ponder on this for a bit, and see if we can't come up with something other than just disabling the systemd security precautions outright.

**Comment by rubenk** [comment]
> Some of the challenge lies in supporting Cent6 where epel is not quite as current with the collectd updates.

Well that's the conundrum, EPEL is meant for enterprise systems, so it can't give you the latest and greatest version of collectd and at the same time promise stability.

But I feel your pain, I still do my own builds of Collectd 5 for CentOS 6. There is a plan which is a bit stalled to offer it in EPEL6 too next to Collectd 4 (https://bugzilla.redhat.com/show_bug.cgi?id=1308742).

One thing I apologise for was misjudging the impact of the capability restriction and not mention it in the release notes. We'll strive to do better, but in return, it would help if users would test master more often because it has been in there for a while before it landed in a stable version.
