### ISSUE TITLE
ipmi matching sensor problem

### ISSUE THREAD

**Issue by f1-outsourcing** [collectd/collectd#2642]
If I put IgnoreSelected false, I dont seem to be able to chatch the sensor data. I have tried with the below 3 strings. For now I have put IgnoreSelected true to catch all data. 

```
<Plugin ipmi>
    # maybe add powersupply presence
    #
    # don't know how to select just a few sensors
    # so for now getting all
    #
    Sensor "CPU1 Temp"
    Sensor "CPU1 Temp processor"
    Sensor "CPU1 Temp processor (3.1)"

    IgnoreSelected true
    NotifySensorAdd false
    NotifySensorRemove true
    NotifySensorNotPresent false
    NotifyIPMIConnectionState false
    SELEnabled false
    SELClearEvent false
</Plugin>
```

Data is stored by influxdb like this
ipmi_value,host=c01,type=temperature,type_instance=CPU1 Temp processor (3.1)
ipmi_value,host=c01,type=temperature,type_instance=CPU2 Temp processor (3.2)
ipmi_value,host=c02,type=temperature,type_instance=CPU1 Temp processor (3.1)
ipmi_value,host=c02,type=temperature,type_instance=CPU2 Temp processor (3.2)

**Comment by rpv-tomsk** [comment]
Hi!

Thanks for the report. As I understand, this already fixed in https://github.com/collectd/collectd/pull/2629

Please, fill issue reports with use of a provided template, at least you have to specify Collectd version where you found the problem.

If you have another issue, not related to #2629, please feel free to reopen the issue.
