### ISSUE TITLE
Filter by data source / usefulness of data sets in general

### ISSUE THREAD

**Issue by hontvari** [collectd/collectd#2671]
I wanted to reduce the number of Graphite values by only storing the longterm load value. It seems to be that this is not possible for several reasons. The regex matcher cannot match a specific data  source, because it matches complete data sets. Nor is there a target, which would remove a data source from a data set.

After thinking about this, I see no benefit of data sets. On the other hand they are confusing:
- They break the usual structure of graphite, write_log naming 
- They are not predictable: a plugin can provide several data values in two ways:
  - Using the usual identifier naming schema, with several TypeInstance values each containing a single value
  - Using a single TypeInstance with a data set containing multiple data sources
- Based on the graphite, etc. name, it cannot be determined that a value is coming from a TypeInstance of a Data source.
- Plugin wiki / man page does not document if the value is part of a multiple value dataset or not. 
- There is no support for this concept in graphite.

I can only imagine a single benefit: the data set can consistently represent several values from a single measurement. However, because there is no support for data sets in other tools, this benefit is not realized.

Could you please explain what is the benefit of storing multiple values in a single data set instead of storing values one-by-one? Would it be possible to simplify Collectd by removing the data set concept?

**Comment by rpv-tomsk** [comment]
Short answer: Universe is not ideal.

>They break the usual structure of graphite ...
>Based on the graphite, ...
>There is no support for this concept in graphite.

The Collectd project was started in 2005. It has no goal to be a data collection agent for Graphite, which was started a year later, and it has no such goal currently (AFAIK).

>Plugin wiki / man page does not document if the value is part of a multiple value dataset or not.

You can improve that, I think. 

> ... there is no support for data sets in other tools, this benefit is not realized.

This opinion is wrong. Example: `rrdtool`.
You can implement support of data sets in graphite, if needed.

>Would it be possible to simplify Collectd by removing the data set concept?

As for me, I take it as rhetorical question.  
The absence of data sets concept in some of tools cannot be a reason for removal of such concept from Collectd. But you can try. 

---
This issue was opened more than three months ago. 
So, I will close it now, as I think it is answered.
Feel free to reopen it if you have further questions.

Thanks for using Collectd.
