### ISSUE TITLE
Build failing: syntax error near unexpected token `$am__api_version,lt,1.12,'

### ISSUE THREAD

**Issue by rcmendru** [collectd/collectd#2674]
*   Version of collectd: Building the latest collectd from "git clone https://github.com/collectd/collectd.git""

*   Operating system / distribution: RedHat 6.5

## Expected behavior

After cloning, I am trying to do the following:
./build.sh
./configure --with-librdkafka=/usr --without-perl-bindings --enable-perl=no
And I expected this to succeed. This is working fine on CentOS7 and also Ubuntu. It is failing in RHEL6.5.

## Actual behavior
./configure command is failing with the following error:
./configure: line 37421: syntax error near unexpected token `$am__api_version,lt,1.12,'
./configure: line 37421: `AX_COMPARE_VERSION($am__api_version,lt,1.12,'

## Steps to reproduce
Install RedHat 6.5 and other packages.
	$ git clone https://github.com/collectd/collectd.git
	$ ./build.sh
	$ ./configure --with-librdkafka=/usr --without-perl-bindings --enable-perl=no
I have already build librdkafka successfully from https://github.com/edenhill/librdkafka.git.

I am relatively new to RHEL and building the package from the source in git. Hence, any help and guidance is appreciated.

Thanks.

**Comment by kwiatrox** [comment]
Hi @rcmendru 
I had similar problem once.
It is due to missing AX_COMPARE_VERSION macro on RedHat 6.5. It is part of autoconf-archive.
I've installed it manually from https://www.gnu.org/software/autoconf-archive/Downloads.html .
Installation was straightforward:
`./configure && make && make install`

For me it solved the issue.

**Comment by vtols** [comment]
Likely you need `./configure --prefix=/usr`

**Comment by rubenk** [comment]
The AX_COMPARE_VERSION macro is included, so there's no need to download the autoconf archive.

@rcmendru if you're not familiar with building from git, it's probably best to build from tarballs or just use our pre-built packages.

**Comment by vtols** [comment]
@rubenk it didn't work for me, for some reason.:disappointed:
In case I have need to build from source, how should I run build script to make use of this macro, that's in m4 directory?

**Comment by rubenk** [comment]
If you're building from tarball, you don't need to run ./build.sh, just `configure && make && make install` as described in the README.

**Comment by vtols** [comment]
@rubenk I understand it, but I need to build from source (git clone).

**Comment by rubenk** [comment]
@vtols just running ./build.sh should be enough.

**Comment by kwiatrox** [comment]
@vtols, @rubenk It may be a question of automake version.
I reproduced this issue on CentOS 6 with automake 1.11.1. What version of automake do you have?

According to documentation:

> "The search path for local files, as of version 1.13 of automake, is defined by the directories listed in AC_CONFIG_MACRO_DIR and AC_CONFIG_MACRO_DIRS arguments. Previously, it was common to use a variable defined in Makefile.am (ACLOCAL_AMFLAGS) to pass extra parameters to aclocal. This behaviour is deprecated and will soon not be supported."

The collectd uses AC_CONFIG_MACRO_DIR in configure.ac. The macro ACLOCAL_AMFLAGS in Makefile.am is set, but it seemingly takes effect if autoreconf is used.

So the workaround is to:
Change build.sh to directly point aclocal to m4 directory:
```
-&& aclocal \
+&& aclocal -I m4 \
```

Or just use `autoreconf -iv` instead of `build.sh`. In this case it should work, but I'm not sure about possible side effects.

**Comment by rubenk** [comment]
@kwiatrox ah yes that must be it. To be honest I always just use autoreconf -vif. Just pushed a fix for build.sh, thanks.
