### ISSUE TITLE
Fail to compile src/libcollectdclient/client.c (lcc_version)

### ISSUE THREAD

**Issue by ymettier** [collectd/collectd#272]
Hello,

I have a compilation problem :

```
client.c: In function ‘lcc_version’:
client.c:563: error: ‘upstream’ undeclared (first use in this function)
client.c:563: error: (Each undeclared identifier is reported only once
client.c:563: error: for each function it appears in.)
```

What is "upstream" ? The answer is here :

```
$ git describe 
collectd-upstream-20130306-54-g81e9ac9
```
(yes, I use tags for myself too)

Explanation : git describe is supposed to return something like collectd-M.m.µ-* where M, m and µ are numeric. If you tag something different, M will not be numeric and the prototype of lcc_version() will conflict.

Here is a patch for version-gen.sh that will test if M is numeric (it seems that there is no need to est if m and µ are numeric) :

```
diff --git a/version-gen.sh b/version-gen.sh
index e344541..6c8e466 100755
--- a/version-gen.sh
+++ b/version-gen.sh
@@ -10,4 +10,8 @@ fi
 
 VERSION="`echo \"$VERSION\" | sed -e 's/-/./g'`"
 
+if [ ! `echo $VERSION | cut -d. -f 1 | grep "^[[:digit:]]*\$"` ]; then
+       VERSION="$DEFAULT_VERSION"
+fi
+
 echo -n "$VERSION"
```

Regards,
Yves

**Comment by rubenk** [comment]
Hi Yves,

Yeah, version should be numeric. Testing for this in a portable manner which works on all platforms is tricky though. Since this script is used by autoconf itself we can't use configure to check for a portable grep etc.

Since 1415c4ed9149c134813368caf728a79fd6e69800 we at least check if the tag contains 'collectd'. You can use tags if you name them something else (so 'upstream-20130306' would work for example). Is that a workable solution for you?

**Comment by ymettier** [comment]
Hello,

Well, I think it should be OK.

Regards,
Yves
