### ISSUE TITLE
collectd without rrdtool?

### ISSUE THREAD

**Issue by leeoniya** [collectd/collectd#2996]
collectd itself seems to be lightweight but the published apt `collectd` package pulls 215 dependencies, including openjdk-11-jre-headless and an install size of 391MB.  i was pretty astonished by this - i simply want to log metrics into a CSV file with logrotate. it looks like a lot of the dependency bloat comes from plugins, especially rrdtool.

https://github.com/voidlinux/void-packages/issues/5463

is there a prepackaged version of `collectd-light` or similar that excludes a lot of this bloat or am i stuck compiling everything from sources? i have limited experience with building from sources and troubleshooting build errors on linux machines.

thanks!

**Comment by rpv-tomsk** [comment]
Hi!

`Collectd` package has no strong dependency on libraries, used by plugins - only `Recommends`, not `Depends`. So, you just have to don't install unneeded dependencies.

Also, you might to use `collectd-core` package. It also has no strong dependencies, `Suggests` instead of `Depends`.

Thanks for using Collectd.

**Comment by leeoniya** [comment]
ok, i'll try that, thanks!
