### ISSUE TITLE
dns plugin: Rewriting numeric qtypes to strings depends on symbols that have been removed from newer glibc versions  

### ISSUE THREAD

**Issue by usev6** [collectd/collectd#3145]
*   Version of collectd: 5.8 (and older)
*   Operating system / distribution: Linux / CentOS 7 (probably other OS/distros that use glibc, too)

## Expected behavior
Metric names for qtypes should have the name of the resource record type -- e.g. ```dns_qtype.A```

## Actual behavior
Metric names for qtypes contain the numeric id of the resource record type with a ```#``` prepended -- e.g. ```dns_qtype.#1```

## Steps to reproduce
I've encountered this behaviour (numeric ids are no longer rewritten to the names of the resource record types) after an upgrade from collectd-5.8.0-3.el7 to collectd-5.8.0-4.el7 on CentOS 7. I've opened a bug report in the Fedora EPEL about the problem with the new package: https://bugzilla.redhat.com/show_bug.cgi?id=1706350

I think the underlying reason is in the code base of collectd, namely that the code in ```src/utils/dns/dns.c``` looks for the symbols ```__NAMESER``` and ```__BIND``` and falls back to the numeric type ids if those are not defined (this happens in qtype_str, cmp. https://github.com/collectd/collectd/blob/55cf383915/src/utils/dns/dns.c#L667). Since newer versions of glibc have removed those symbols (cmp. https://sourceware.org/git/?p=glibc.git;a=commit;h=006768c72a), the checks should be adjusted. I don't know how to do that in a clean way. Maybe just looking for ```HAVE_ARPA_INET_H``` would be good enough for the basic resource record types?

Please take my analysis with some salt -- I might be wrong about the cause of the problem.

**Comment by usev6** [comment]
I've continued to wonder how a clean fix would look like. I don't really understand why the code in ```qtype_str``` uses the enum values from ```arpa/nameser.h``` like it does. Maybe you could help me to understand that?

Even with the initial commit of the (at that time new) dns plugin, ```qtype_str``` used symbols from ```arpa/nameser.h``` (or ```arpa/nameser_compat.h```) for the different cases of the switch statement: https://github.com/collectd/collectd/commit/1e7b5f4e24#diff-2706c7320cd0104beeb5a589d34db8b0R800

The next function in that file, ```opcode_str``` just used integers instead: https://github.com/collectd/collectd/commit/1e7b5f4e24#diff-2706c7320cd0104beeb5a589d34db8b0R854

I wondered if we could just go and use the integers from ```arpa/nameser.h``` to translate back to resource record names (as it is done in ```opcode_str```).

```
const char *qtype_str(int t) {
  static char buf[32];
  switch (t) {
  case 1:
    return "A";
  case 2:
    return "NS";
  /* [...] */
  default:
    snprintf(buf, sizeof(buf), "#%i", t);
    return buf;
  }
}
```

Are there implementation of nameservers around that don't follow the RFC and where the dns plugin get's different integers (while the symbols would still be right)?

**Comment by rpv-tomsk** [comment]
Added a PR to solve this issue.

**Comment by usev6** [comment]
I's a pity that this bug wasn't fixed with 5.9.0 -- especially since @rpv-tomsk created a PR about a month before the release.

However, I guess that happened due to [ENOTUITS](https://en.wiktionary.org/wiki/ENOTUITS)

**Comment by rpv-tomsk** [comment]
Before #2958 changes I was able to do merges of my own changes.
Now I have no such permission. And nobody other takes care. I am absolutely not happy to wait for months until the changes are merged. Often, due to unstable project policies, these changes become inactual due to formatting or style changes.  This leads to the need for additional work and is completely unacceptable.

There also was many new plugins, prepared for new release, but not included.
This disrespect for the authors and it reduces the desire to develop a project.
We even have not updated https://github.com/collectd/collectd/blob/master/ChangeLog

https://github.com/collectd/collectd/milestone/13

From my POW,  Team prevents other people from project developing and project is buried.

From day to day I am more and more thinking to leave the "Trusted Contributors" group as by the fact I'm not trusted.

**Comment by rpv-tomsk** [comment]
> I am absolutely not happy to wait for months until the changes are merged.

... for months and years.
