### ISSUE TITLE
Collectd community calls - biweekly or monthly?

### ISSUE THREAD

**Issue by sunkuranganath** [collectd/collectd#3356]
Hello friendly Collectd community,

As was discussed in community meetup earlier this year, many have expressed interest in having community calls with regular cadence. Its about time we establish something to start with.
We could use this forum to discuss wide variety of issues - pending PRs, merge requests, build failures, validation, CI, code contributions, ownership, etc.

https://github.com/collectd/collectd/issues/3354 suggests we dont want to spend too much time on Slack etc., but rather required focus on code, which I agree. However we do need way to effectively communicate and nothing is better than speaking to each other.

To that end I can personally take responsibility to setup and run the community webex calls. Now question remains on time, frequency and day of the week. We would want to accommodate as many folks across many different countries and time zones. 
I have listed few options below considering our team's availability but we are very much open to more possibilities. 
Please indicate your preference on below:
1. Bi-weekly, alternate Thursday, 2PM UTC/6AM PST, 1 hour duration
2. Bi-weekly, alternate Monday, 2PM UTC/6AM PST, 1 hour duration
3. Monthly (once a month), Monday/Thursday, 2PM UTC/6AM PST, 1 hour duration

Personally I would prefer 3PM or 4PM UTC, but will leave the choice to the community.
Please note that our team is flexible to accommodate as many volunteers as possible. 

PS: Was on sabbatical and just catching up with the open issues.

Thanks,
Sunku

**Comment by jkanhir** [comment]
Hi Sunku, 

It's a great idea to have a community call for collectd. This initiative is appreciated. 
I would prefer Bi-weekly, alternate Monday, 3PM UTC/7AM PST, 1 hour duration. 

Thanks, Jabir

**Comment by mrunge** [comment]
https://github.com/collectd/collectd/issues/3354 states, we don't need more communication channels, we need issues solved.

I'm happy to try a bi-weekly call, preferably on Monday.

**Comment by kkepka** [comment]
+1 to at least give it a try and spin up momentum, Mondays sounds good to me as well.

**Comment by mkobyli** [comment]
Bi-weekly call on Monday sounds good to me.

**Comment by rubenk** [comment]
@sunkuranganath we'd like to reserve the github issue tracker for actual technical issues in Collectd. These kinds of requests are better directed at the mailing list.

As for your actual proposal, I understand the desire for community calls, but I don't think they solve anything at this point. For one, they actually create the feeling, at least for me, that there's stuff happening behind closed doors. I wasn't able to attend the meeting at Fosdem last year and still feel left out because it seems that there were some decisions made there without my involvement. I'd rather have those discussions in public, on the mailing list, or where needed in issues on Github.

The last thing I'd like to say is that I think there's enough discussion already, but nobody who actually does the work, and adding more process doesn't help. 

At this point there doesn't seem to be anyone around with access to the CI or the website. Having conference calls without those people calling in won't solve anything. There's also only about 3 people actually looking at PRs and issues, Intel could start with helping out there as well instead of adding plugin after plugin.

**Comment by kwiatrox** [comment]
For me Monday and Thursday are good as well for 2PM UTC, but would prefer Thursday in case of later time.  I would vote to start with bi-weekly meetings and after some time decide to stay with that or switch to monthly cadence.

**Comment by mrunge** [comment]
> As for your actual proposal, I understand the desire for community calls, but I don't think they solve anything at this point. For one, they actually create the feeling, at least for me, that there's stuff happening behind closed doors. I wasn't able to attend the meeting at Fosdem last year and still feel left out because it seems that there were some decisions made there without my involvement. I'd rather have those discussions in public, on the mailing list, or where needed in issues on Github.

We really missed you there! I tried to blog about it http://www.matthias-runge.de/2019/02/04/collectd-meetup-bru/ in order to be as open and inclusive as possible.
All this was about to get everyone on the same page and to move the project a bit forward. We can not afford to exclude anyone.

From my experience, such calls do form a bit of a community (at least among those, who happen to be on the call). I understand, not all of us would be able to attend regularly (or at all). It's not perfect.

I would like to get more people on board, and involved. Especially we need people working on CI. We even have at least one volunteer (@faxm0dem ) for this task, but he lacks permission.
That is something we should fix ASAP. If anyone able to talk to @octo , please mention this to him and ask for giving permissions.

**Comment by sunkuranganath** [comment]
@rubenk  absolutely agree with you on what's important. There is nothing more urgent and important than to resolve the pending issues, fix our CI and help review other's code.
Like @mrunge  mentioned above, reviewing issues becomes easier & faster once some of us are able to communicate over a call. We should surely continue to use github issue tracker, leave a github/IRC trail & continue to use github/IRC as much as possible, no doubt. 

I will give slightly different perspective based on things that happened in 2019:
- F2F discussions at meetup back in Jan 2019 (as captured by @mrunge) gave a good motivation for folks to resolve few issues, enabled 2 releases and essentially keep community alive
- We discuss lot of Collectd at weekly OPNFV Barometer calls, a project that heavily relies on Collectd catered for Telco environments. Between the participants of the call, it helped review each other's PRs, issues and create a sense of urgency to help each other. Similar approach could be applied here
- Our team (in Intel) is preparing to open source our internal Collectd validation & CI code so everyone in community can benefit. This may not be one size fits all but surely helps community overall. This is a topic of discussion at upcoming meetup (https://etherpad.openstack.org/p/collectd-meetup-2020)
- First time code contributors and Collectd users our team have dealt with were lost about community workings, figuring out how to get help, etc.
- Our team is committing to spend more time reviewing overall community issues going ahead

Having said above, to ease the review process, CI and/or release issues, a simple call might help to fix issues faster. To that end I can schedule a call on experimental basis for next 3 months to evaluate its effectiveness in resolving open issues. Interested folks could join in. If it proves effective in progress towards closing issues, we could continue.

**Comment by sunkuranganath** [comment]
To that end I have setup a bi-weekly webex call on Mondays (as Monday seems to be most popular), 7AM PST/3PM UTC, starting January 6th 2020. I have sent the invite to collectd@verplant.org. 

For those that havent subscribed to Collectd mailing list, here is the meeting info
Meeting link: https://intel.webex.com/intel/j.php?MTID=m8cc6137cce69623a982e8e69a0e8c7c7
Meeting number: 593 350 778
Passcode: @Collectd2020

Meeting times or any other concerns could be discussed on the first call on Jan 6th 2020.
Hoping towards good progress on closing the issues.

**Comment by sunkuranganath** [comment]
Now that we have ongoing bi-weekly calls, it was decided to capture all the details on the Collectd wiki.
Link: https://collectd.org/wiki/index.php/Community_calls 

Interested folks are welcome to join. We could close the issue.
