### ISSUE TITLE
write_mongo doesn't work with ./configure

### ISSUE THREAD

**Issue by dothak** [collectd/collectd#492]
Using mongo-c-driver v0.9
./configure output: http://pastie.org/8509965
make output: http://pastie.org/8509950

**Comment by jbergstroem** [comment]
I think it's time to move to mongo-c-driver. We should probably switch to checking through pkg-config as well.

**Comment by ChrisLundquist** [comment]
From the [current Readme](https://github.com/mongodb/mongo-c-driver/tree/221708f15c4ab12a881f1a3bd597c8614534f5d5)

> There are absolutely no guarantees of API/ABI stability at this point. But generally, we won't break API/ABI unless we have good reason.

> mongo-c-driver depends on Libbson. Libbson will automatically be built if you do not have it installed on your system.

Means that even though they are > 1.0 they might still break the API (presumably they mention this because they will at a less than major release version)

This is a little worrying.

Looking at the make output @dothak posted it seems they (?re)moved `bson_create` and `bson_dispose`

I took a quick look right now, and it seems at against mongo-c-driver 1.1.7 there are a few things that need to change. Currently, we can't even build write_mongo using the latest driver.

- [ ] Fix configure.ac to look for `<mongoc.h>` instead of `<mongo.h>`
- [ ] Add libbson to configure.ac

Once we have it building again, then we can go about updating things.

**Comment by jbergstroem** [comment]
@ChrisLundquist do we really have to check for libbson? It's implied if using mongo-c-driver >1.0. If we use pkg-config to check for libmongo-c-1.0 we'd get proper linking/include details as well.

**Comment by ChrisLundquist** [comment]
I agree it is implied. Shouldn't we let someone specify a libbson path though( if we can't figure it out)?

Currently the only way I can get a test program to include those headers looks like this:
`gcc -c -g -O2 -I/usr/local/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0 ./test.c `

`mongoc.h` has `#include <bson.h>` in it, so we have to make that work.

Note that currently `configure.ac` basically checks for `$prefix/include/mongo.h` and `$prefix/lib/libmongo` which no longer works because they are in the `libmongoc-1.0` folder.
I'm not sure if this is just the case on OS X, or if they are installed this way on RHEL / Debian as well.

@jbergstroem It sounds like you might know more about M4 macros / autotools / etc than I do. If you can fix that part up, I can take a look at the C part.

**Comment by jbergstroem** [comment]
@ChrisLundquist already on it. I will take the pkg-config route for now. If people insist to provide path we'd need (as you also state) bson include path as well.

**Comment by jbergstroem** [comment]
(fyi)
```bash
(test) ~/collectd ±mongo-c-driver-1.0 # pkg-config --cflags libmongoc-1.0 
-I/usr/include/libmongoc-1.0 -I/usr/include/libbson-1.0 
(test) ~/collectd ±mongo-c-driver-1.0 # pkg-config --libs libmongoc-1.0
-lssl -lcrypto -lrt -lmongoc-1.0 -lbson-1.0 
```

**Comment by ChrisLundquist** [comment]
I have `./configure --enable-write_mongodb --with-libmongoc=/usr/local/` "working" with this https://gist.github.com/ChrisLundquist/ccf37f699011cd5777b9

For some reason I can't drop `--with-libmongoc=/usr/local` even though gcc should look there.

**Comment by ChrisLundquist** [comment]
https://github.com/collectd/collectd/compare/master...ChrisLundquist:fix-write-mongodb?expand=1

Here is a rough draft of the needed changes. I can't link `write_mongodb.c` because something still is using `mongoc` instead of `mongoc-1.0`

**Comment by jbergstroem** [comment]
Try this rudimentary diff for the auto* https://gist.github.com/jbergstroem/f25202f6f2178dd42304

**Comment by jbergstroem** [comment]
@octo thoughts on how to handle potentially passing `--with-bson` (required by libmongoc which passes the include path through pkg-config)?

**Comment by ChrisLundquist** [comment]
> Edit: Baked a full patch that compiles/links for me and updated link.

Cool, I think that patch is close. I had some TODO comments to actually honor the passed host,password, etc we should because to snprintf into a char[1024] or something and then pass that to `mongoc_client_new` rather than the currently hardcoded `localhost`

**Comment by jbergstroem** [comment]
@ChrisLundquist sounds good to me. I can look at adding `--with-libbson` in case we go for it.

**Comment by mfournier** [comment]
@ChrisLundquist @jbergstroem I just  wanted to be sure you've seen #863. Thanks !

**Comment by synthmeat** [comment]
Wrt "no one using this"... I tried. :)

**Comment by wtps0n** [comment]
I think it's good place to continue this issue not creating new one. I'm FreeBSD collectd port maintaner. I tried build with write_mongo plugin, but it is not building correctly. I've made a patch to configure.ac to support correctly mongo-c-driver. But there is errors during compiling. You can check logs and patches:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=206660
https://rtm.bsdserwis.com/poudriere/data/a1amd64-testing/2016-02-01_01h52m21s/logs/errors/collectd5-5.5.1.log

So it seems that this plugin should be rewritten to new version of mongo-c-driver. As I can see it has law priorytet.

**Comment by saiarcot895** [comment]
I've made some changes to the patch @jbergstroem made to make writing to mongodb work, and the new patch is [here](https://gist.github.com/saiarcot895/de4046a803c428ffb25dac296c7f2022). However, I'm planning on making some changes to the format the data is stored for better efficiency, based on [this](https://www.mongodb.com/blog/post/schema-design-for-time-series-data-in-mongodb) blog post.
