### ISSUE TITLE
libjvm not found

### ISSUE THREAD

**Issue by bijugs** [collectd/collectd#635]
Trying to configure the JAVA plug-in to use GenericJXM feature.The configure step is failing with libjvm not found. 
libjvm  . . . . . . . no (libjvm not found)

The following is the configure command used. I have formatted a little bit for readability and /usr/lib/jvm/java-1.7.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/amd64/server directory has libjvm.so. Any help in resolving this issue is much appreciated.

./configure --with-java=/usr/lib/jvm/java-1.7.0-openjdk-amd64 JAVA_

CPPFLAGS="-I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/amd64/server -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include/linux" 

JAVA_CFLAGS="-I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/amd64/server -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include/linux" 

JAVA_LDFLAGS="-I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/amd64/server -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include/linux -I/usr/lib/jvm/java-1.7.0-openjdk-amd64/include" JAVA_LIBS="-l/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/amd64/server -l/usr/lib/jvm/java-1.7.0-openjdk-amd64/include" 

JAR="/usr/bin/jar" JAVAC="/usr/bin/javac" --enable-write_graphite --enable-java

**Comment by c-hoeger** [comment]
Since I am stumbling over the same problem now on Wheezy:  can you please tell me what is the place to set LD_LIBRARY_PATH and/or LD_PRELOAD?
I tried /etc/default/collectd, but that doesn't help.

The only working way I found is described here: https://bugzilla.redhat.com/show_bug.cgi?id=1212151#c2 (adding a file /etc/ld.so.conf.d/java.conf) pointing
to the path containing libjvm.so
