### ISSUE TITLE
[tail plugin - does not preserve the last parsed line between collectd restarts]

### ISSUE THREAD

**Issue by ser** [collectd/collectd#642]
When you restart collectd, tail plugin parses the file from the beginning, which makes total mess in stats. 

It should preserve the last analysed line during collectd shutdown.

**Comment by notpeter** [comment]
My assumption was that the tail plugin would follow a given file emitting data as new log entries were written.  I can't imagine any scenario where the current behavior is desirable. I don't believe collectd has an existing framework for persisting plugin state (e.g. file offset) between invocations. So I'm propose the default tail plugin behavior be changed to follow the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Specifically, only handle lines in a log file which are written while the plugin is running, e.g. from the TAIL of the opened when a log rotation has occurred (inode change, offset beyond EOF) when the entire contents of the file is read to catch up.

I'm totally ok with my collectd counters being incorrect for time while collectd wasn't running, where as currently anytime collectd is restarted (config changed, pkg upgraded, system rebooted) the tail plugin greedily consumes the entire file and emit a crazy town value.

Thoughts?

See: [Plugin:Tail docs](https://collectd.org/wiki/index.php/Plugin:Tail)

**Comment by rpv-tomsk** [comment]
This issue is not confirmed.  Mentioned "total mess in stats" may be caused by incorrect ds-types in used datasets or in `DSType` option.

Tail plugin has logic to do EOF seek on file first open since 2008, and it works. My simple tests confirm this.
Code Example: https://github.com/collectd/collectd/blob/b978177200519893f6ff9c5e459a3d9d6a72b887/src/utils_tail.c#L41

If you have any thoughts please open new issue, I will take care.

**Comment by ser** [comment]
I do not understand that piece of code, how a restarted collectd instance knows it re-opens the file and which line number, where that information is stored between restarts?
