### ISSUE TITLE
write_influxdb plugin

### ISSUE THREAD

**Issue by ghost** [collectd/collectd#696]
Please add a plugin for write the data collected directly influxdb (http://influxdb.com/) Now we use the Diamond (https://github.com/BrightcoveOS/Diamond) to collect and write data, but would like to use collectd. We looked collectd-influxdb proxy (https://github.com/bpaquet/collectd-influxdb-proxy), but would not want to use it as an additional point of failure.

**Comment by damm** [comment]
+1 being able to select carbon or http for write to influxdb would be :)

**Comment by elnappo** [comment]
There should be a write_influxdb plugin. The InfluxDB graphite and collectd inputs both lacks encryption and authentication.

**Comment by damm** [comment]
Indeed there should be.  Getting people to support the collectd protocol doesn't feel right.

**Comment by ranjanmanish** [comment]
This will be helpful as in case of write_tsdb we have option to tag the data before sending it out. Write write_influxdb will help us changing the source code to get it to do the same.

**Comment by aferrari-technisys** [comment]
here the way that will work, write_tsdb will be compatible with Influxdb>= 0.9

https://github.com/collectd/collectd/pull/1107

**Comment by inthecloud247** [comment]
The write_graphite and write_tsdb plugins are limited since with influxdb you can only specify one database to use for all of the graphite or tsdb traffic, and there's no authentication. With an influxdb plugin like this ( https://github.com/wenbinye/influxdb-collectd-write ) you can support authentication and use of different influxdb databases.
