### ISSUE TITLE
Pipe leak when plugin attempts to run with incorrect user

### ISSUE THREAD

**Issue by mhollick** [collectd/collectd#762]
Collectd version 5.4.1

Our collectd is configured to execute plugins as user 'collectd'.
A configuration management error removed this user account.
This resulted in a stream of (expected) errors like:

````
[2014-10-09 13:52:48] [error] exec plugin: No such user: `collectd'
````
running:

````
maxwell$ sudo lsof -c collectd | grep pipe
collectd  876 root   11r  FIFO                0,8      0t0 5672190 pipe
collectd  876 root   12w  FIFO                0,8      0t0 5672190 pipe
collectd  876 root   13r  FIFO                0,8      0t0 5672191 pipe
collectd  876 root   14w  FIFO                0,8      0t0 5672191 pipe
collectd  876 root   15r  FIFO                0,8      0t0 5672192 pipe
collectd  876 root   16w  FIFO                0,8      0t0 5672192 pipe
````

returns a growing number of FIFO pipes which eventually exhaust available file handles.
At some point, the unix control socket stops responding and most metrics stop flowing (uptime continues to work).

**Comment by mfournier** [comment]
Closed by 94e5622, thanks to @gautambt's patch in #933. The fix will be part of upcoming 5.5.1 and 5.4.3 releases.

**Comment by rrajaram** [comment]
Hi,
Could you please confirm if the fix will be available in 5.5.1 release. We are running collectd 5.4.0 where we see similiar symptoms related to /var/log/mesages  showing multiple "exec plugin: fork failed: Cannot allocate memory"  in production env.
Restarting collectd service solves the problem temporarily. 
Have upgraded to collectd 5.5. But have not seen this fixed in the changeLog.
https://github.com/collectd/collectd/blob/collectd-5.5/ChangeLog

Also is this anyway related to the available free memory.
free -m shows only 788k available.

         total  used  free shared buffers cached
Mem: 64427 63638 788  0      378     4711
-/+ buffers/cache: 58548 5878
Swap: 3967 3967 0

**Comment by mfournier** [comment]
Yes, I confirm. Currently you have 2 options: build from the git tree or use the nightly builds: https://github.com/collectd/collectd-ci

**Comment by rrajaram** [comment]
Hi
Thanks for the response.I assume the confirmation is for the availability of the fix in 5.5.1 release
Can you also comment on Is the error related to available free memory on the box? I mean when the available free mem is too low will we hit the error  "exec plugin: fork failed: Cannot allocate memory" .

**Comment by rrajaram** [comment]
Team,
Can you confirm if one can hit the error "exec plugin: fork failed: Cannot allocate memory" when the memory is low  - 788KB as below. 
#free -m
total used free shared buffers cached
Mem: 64427 63638 788 0 378 4711
-/+ buffers/cache: 58548 5878
Swap: 3967 3967 0

**Comment by octo** [comment]
@rrajaram a low memory situation sounds like a likely cause for the error you're seeing. I don't think that this bug causes these low memory situations though, but that low memory situations can trigger this bug.
