### ISSUE TITLE
nginx plugin: support several instances

### ISSUE THREAD

**Issue by landryb** [collectd/collectd#780]
more a feature request than an actual bug.. there's been a patch a while ago on the collectd mailing list to support multiple nginx instances in the nginx plugin (see https://www.mail-archive.com/collectd@verplant.org/msg02497.html) and it seems to have been missed/ignored. The proposal was to use the same layout as the apache plugin with <instance> xml childs.

What would it take to get it properly integrated ?
What should be done for a migration from the old-style to the new-style (move rrds around) ?

**Comment by pauvos** [comment]
No updates since 2014? I agree that nginx plugin should provide roughly the same functionality/syntax as the apache plugin.

There is also some free-of-context proposal at stackoverflow containing just 3 lines: http://stackoverflow.com/questions/20739397/adding-multiple-nginx-to-collectds-monitoring-plugin

Unfortunately I'm not an expert c-coder. :/

**Comment by cvle** [comment]
That's rather disappointing :-(

**Comment by octo** [comment]
Patches are always welcome. That snippet from StackOverflow doesn't implement this feature though.

**Comment by octo** [comment]
Closing ancient feature request due to lack of interest.
