### ISSUE TITLE
memcached plugin: Unexpected hostname "127.0.0.1".

### ISSUE THREAD

**Issue by Poil** [collectd/collectd#801]
Hi,

Multi-instances doesn't seem to work on collectd 5.4 :

```
LoadPlugin memcached
<Plugin "memcached">
  <Instance "default">
    Host "127.0.0.1"
    Port 11211
  </Instance>

  <Instance "session">
    Host "127.0.0.1"
    Port 11213
  </Instance>

  <Instance "storage">
    Host "127.0.0.1"
    Port 11212
  </Instance>
</Plugin>
```

Ref: http://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_memcached

Strace output seem to be ok (for each instance) : 
```
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 7
connect(7, {sa_family=AF_INET, sin_port=htons(11211), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
write(7, "stats\r\n", 7)                = 7
recvfrom(7, "STAT pid 11499\r\nSTAT uptime 1303"..., 4096, 0, NULL, NULL) = 1130
shutdown(7, 2 /* send and receive */)   = 0
close(7)                                = 0
```

**Comment by CyBeRoni** [comment]
Having just run into this, it works if you remove the <instance> parts of the configuration. The plugin then uses a legacy configuration mode which does use the correct hostname.

The problem lies here: https://github.com/collectd/collectd/blob/master/src/memcached.c#L259. It should use hostname_g there rather than st->host.

**Comment by mfournier** [comment]
@Poil @CyBeRoni do you have a way to test the patch mentioned above ? Thanks !

**Comment by CyBeRoni** [comment]
I can build it and try it, but see my comment on the commit first.

**Comment by Poil** [comment]
Hi,

First thanks for this patch, I'll try to test it in the next week.

I +1 CyBeRoni, today we have 4 differents way, depending of plugins, "to which hostname to write", I think it'll be cleaner to have a generic function to do this job and to normalize this.

Here is a quick inventory :
- Write to collector hostname only but target host (or url) is configurable
Apache, Ascent, Bind, Curl*, hddtemp, memcached(4), mbmon, memcachec, mysql, nginx(2), redis, Ping(3)

- If localhost write to collector hostname else write to configured host
dbi, mysql, oracle

- Fully configurable
java/genericjmx, libvirt(1), netapp

- Write to target host only
modbus

1: custom format
2: need to improve to support multi-instance
3: I think it's normal
4: Before patch

**Comment by Tendoncs** [comment]
To fix this for myself, I just created a small conf file for memcache. 

memcached.conf

LoadPlugin memcached
<Plugin "memcached">

    Host "127.0.0.1"
    Port 11211

</Plugin>


and drop it in collectd.conf.d on each memcache server and restart each server's service.

**Comment by octo** [comment]
Many other plugins check if the `Host` setting is "localhost" or "127.0.0.1" and use `hostname_g` in that case. This logic is missing in the *memcached plugin*. Also, the default "127.0.0.1" when the "Host" option is not provided is bad and should be `hostname_g` instead.

Since this is a bit on the invasive side this will go in the 5.6 release, not in a patch release.
