### ISSUE TITLE
pidfile can not guarantee that there is only one daemon running on one machine

### ISSUE THREAD

**Issue by andyxning** [collectd/collectd#815]
pidfile can not guarantee that there is only one daemon running on one machine. As the [doc](https://collectd.org/documentation/manpages/collectd.conf.5.shtml) of **PIDFile** said that the pidfile will be overrided. This can cause more than one collectd daemon running with the ones before the last one can not be killed by the pid in the pidfile since it is not their pid.

**Comment by rubenk** [comment]
I agree that this is an issue. This is quite difficult to solve however. Collectd needs to read and write the pidfile in an atomic fashion, preferably without keeping an flock on it and leaving behind stale pidfiles.

**Comment by octo** [comment]
You have to expect left-behind PID files, because if the daemon dies unexpectedly it will be left behind. So what you'd want to do is not start if the PID stored in that file is still running. Since this is implemented in tools such as *start-stop-daemon*, I don't see a need to replicate this behavior in *collectd*. Overwriting is therefore the most sensible action in this case.

*→ working as intended*
