### ISSUE TITLE
RPM: libcollectdclient package doesn't get updated when updating the main collectd package via yum

### ISSUE THREAD

**Issue by behrendsj** [collectd/collectd#879]
Using the spec file in this project I've built a full set of 5.4.1 RPM's.  I have machines that are running collectd 5.3.0.  When I go to upgrade the main collectd package the libcollectdclient package is not upgraded, unlike installed plugins which require the same version as the main collectd rpm.  I'm not sure what type of impact this would have, but it feels like libcollectdclient should require the same version as the main collectd package or vice versa.

**Comment by mfournier** [comment]
@behrendsj: yes, this is because the ABI of libcollectdclient is unchanged between both versions. But I agree these packages should be more tightly coupled, at least to ensure the latest bugfixes in libcollectdclient get pulled down when upgrading collectd.

We can easily force the version dependency on the main collectd package, but I actually think it might be cleaner to do the same as the debian package does: only ship the *daemon* in the main collectd package, and install all the binaries depending on libcollectdclient into their own package (basically, `/usr/bin/collectd-nagios`, `/usr/bin/collectd-tg` and `/usr/bin/collectdctl` would go in collectd-utils.rpm).

What do you think ?

**Comment by behrendsj** [comment]
At the very least I think there should be a dependency set in the main package since it's a very low risk change.    But I do like the idea of mirroring what's being done in debian to simplify things, and if anything make managing a mixed rh an debian environment via a configuration management system simpler.

**Comment by mfournier** [comment]
@behrendsj, I just commited the fix we talked about: a new collectd-utils.rpm which makes the bridge between collectd and libcollectdclient. So no need to install libcollectdclient.rpm when installing the daemon anymore. But if collectd-utils.rpm is installed it will ensure the versions of all the collectd packages are identical.
