### ISSUE TITLE
Statsd: counters always incremented

### ISSUE THREAD

**Issue by duylong** [collectd/collectd#929]
Hi, 

I want to count the error in httpd. I use "increment" method in order to aggregate data with statsd.

For each event, I send this output ```syslog.httpd.error:1|c```

In collectd.conf, I use "DeleteCounters" to true, but it seem that my counter is never reset. My collectd output:

```
[{"values":[1179],"dstypes":["derive"],"dsnames":["value"],"time":1423215320.585,"interval":10.000,"host":"plop","plugin":"statsd","plugin_instance":"","type":"derive","type_instance":"syslog.httpd.error"}]
...
[{"values":[1016],"dstypes":["derive"],"dsnames":["value"],"time":1423215000.585,"interval":10.000,"host":"plop","plugin":"statsd","plugin_instance":"","type":"derive","type_instance":"syslog.httpd.error"}]
...
[{"values":[816],"dstypes":["derive"],"dsnames":["value"],"time":1423214600.585,"interval":10.000,"host":"plop","plugin":"statsd","plugin_instance":"","type":"derive","type_instance":"syslog.httpd.error"}]
...
```
Do you know this issue?

Thank you for your help,

**Comment by octo** [comment]
I think this is due to a misconception what `DeleteCounters` does. The manpage reads:

> These options control what happens if metrics are not updated in an interval. If set to **False**, the default, metrics are dispatched unchanged, i.e. the rate of counters and size of sets will be zero, timers report `NaN` and gauges are unchanged. If set to **True**, the such metrics are not dispatched and removed from the internal cache.

So, if a counter was *not* incremented in the last 10 seconds (or whatever your interval is set to), and this option is enabled, then the metric will be purged to free memory.

Do you have any suggestions how the manpage entry could be improved? Thanks!
—octo

**Comment by duylong** [comment]
You can add a example in order to improve the manpage ;)

What happens if metrics are updated in an interval ? "DeleteCounter" is ignored ? 
I tried the 2 choices, my value is always incremented (I have a sum). Is this normal behavior ?

**Comment by duylong** [comment]
After some tests, no problem with statsd (nodejs app). There a a problem somewhere...

Nobody has this problem using Logstash as client?

**Comment by mikechack** [comment]
Statsd plugin does not behave the same way as the etsy/statsd daemon. I think the true behavior for most statsd implementations for counters is to reset the counter after each sampling period. This is not how the current plugin works. As noted even if the DeleteCounters is set, the value is retained as long as there is a value samled for the current period.

Statsd daemon also has DeleteCounter functionality, but it is used to stop sending values of zero for a counter when there is no new data. It is really orthogonal to reseting the counter after each sampling period, which I think is the standard behavior. The plugin is seriously broken I think.

**Comment by octo** [comment]
Etsy's statsd (or at least their Graphite backend code) emit two metrics for each counter:

 *  The *rate* of change since the last reading. This is what collectd's `DERIVE` metrics are very good at and why counters are mapped to `DERIVE`s in the collectd plugin. This is **working as intended** and will not be changed.
 *  The *delta* to the last reading. One can also quite easily calculate this from `DERIVE`s, but there's hardly any support for it in collectd because it is quite an unusual calculation. That is what #1363 adds (as an option).
